/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package registroVisitasyClima.gui;

import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;
import registroVisitasyClima.dto.Visita;
import registroVisitasyClima.logica.LogicaVisitas;

/**
 *
 * @author Robert
 */
public class RegistroTemperaturas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroTemperaturas.class.getName());

    /**
     * Creates new form RegistroTemperaturas2
     */
    public RegistroTemperaturas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        validaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelTempMin = new javax.swing.JLabel();
        jLabelTempMax = new javax.swing.JLabel();
        jTextFieldTempMin = new javax.swing.JTextField();
        jSpinnerTempMax = new javax.swing.JSpinner();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jButtonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTempMin.setText(org.openide.util.NbBundle.getMessage(RegistroTemperaturas.class, "RegistroTemperaturas.jLabelTempMin.text")); // NOI18N

        jLabelTempMax.setText(org.openide.util.NbBundle.getMessage(RegistroTemperaturas.class, "RegistroTemperaturas.jLabelTempMax.text")); // NOI18N

        jTextFieldTempMin.setText(org.openide.util.NbBundle.getMessage(RegistroTemperaturas.class, "RegistroTemperaturas.jTextFieldTempMin.text")); // NOI18N
        jTextFieldTempMin.setName("Temperatura mínima"); // NOI18N
        jTextFieldTempMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTempMinActionPerformed(evt);
            }
        });

        jSpinnerTempMax.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelTempMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTempMin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelTempMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTempMax)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempMin)
                    .addComponent(jTextFieldTempMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempMax)
                    .addComponent(jSpinnerTempMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButtonRegistrar.setBackground(new java.awt.Color(204, 102, 0));
        jButtonRegistrar.setText(org.openide.util.NbBundle.getMessage(RegistroTemperaturas.class, "RegistroTemperaturas.jButtonRegistrar.text")); // NOI18N
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonRegistrar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTempMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTempMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTempMinActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        try {
             double tempMin = Double.parseDouble(jTextFieldTempMin.getText());
             double tempMax = Double.parseDouble(jSpinnerTempMax.getValue().toString());
             
             // Valida la temperatura
             if (tempMin >= tempMax) {
                JOptionPane.showMessageDialog(this, "La temperatura mínima no puede ser mayor o igual que la máxima", "Revisa temperatura", JOptionPane.WARNING_MESSAGE);
                return;
            }
             
             // Recoge la última visita y le añade lo nuevo
             Visita ultimaVisita = LogicaVisitas.getUltimaVisita();
             LogicaVisitas.getListaVisitas().remove(ultimaVisita); //Borra el anterior registro
             ultimaVisita = new Visita(ultimaVisita.getCiudad(), ultimaVisita.getFechaPrevista(), tempMin, tempMax);
             
             // Añade el registro actualizado
             LogicaVisitas.addVisita(ultimaVisita);
             dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ERROR AL CONVERTIR TEMPERATURA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistroTemperaturas dialog = new RegistroTemperaturas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelTempMax;
    private javax.swing.JLabel jLabelTempMin;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSpinner jSpinnerTempMax;
    private javax.swing.JTextField jTextFieldTempMin;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
/**
     * Validaciones del formulario
     */
    private void validaciones() {
        jButtonRegistrar.setEnabled(false);
        ValidationGroup group = validationPanel.getValidationGroup();

        group.add(jTextFieldTempMin, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextFieldTempMin, StringValidators.REQUIRE_VALID_NUMBER);

        validationPanel.addChangeListener((ChangeEvent e) -> {
            if (validationPanel.getProblem() == null) {
                jButtonRegistrar.setEnabled(true);
            } else {
                jButtonRegistrar.setEnabled(false);
            }
        });

    }

}
