/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import dto.Visita;
import help.Ayuda;
import logica.LogicaVisitas;

/**
 *
 * @author Robert
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    private DefaultTableModel dtm;

    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");

    private Ayuda ayuda;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        mostrarLookAndFeel();
        cambiarIconoApp();
        inicializarTabla();
        ayuda = new Ayuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelImgEstacion = new javax.swing.JLabel();
        jButtonEliminarCiudad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTema = new javax.swing.JLabel();
        jComboLookAndFeel = new javax.swing.JComboBox<>();
        jButtonHelp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemCiudadFecha = new javax.swing.JMenuItem();
        jMenuItemTemperaturas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabelImgEstacion.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jLabelImgEstacion.text_1")); // NOI18N
        jPanel1.add(jLabelImgEstacion);

        jButtonEliminarCiudad.setBackground(new java.awt.Color(153, 0, 0));
        jButtonEliminarCiudad.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jButtonEliminarCiudad.text_1")); // NOI18N
        jButtonEliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarCiudad);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabelTema.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jLabelTema.text_1")); // NOI18N
        jPanel2.add(jLabelTema);

        jComboLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLookAndFeelActionPerformed(evt);
            }
        });
        jPanel2.add(jComboLookAndFeel);

        jButtonHelp.setBackground(new java.awt.Color(0, 102, 102));
        jButtonHelp.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jButtonHelp.text")); // NOI18N
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        jMenu.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jMenu.text_1")); // NOI18N

        jMenuItemCiudadFecha.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jMenuItemCiudadFecha.text_1")); // NOI18N
        jMenuItemCiudadFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCiudadFechaActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemCiudadFecha);

        jMenuItemTemperaturas.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jMenuItemTemperaturas.text_1")); // NOI18N
        jMenuItemTemperaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTemperaturasActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemTemperaturas);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHelp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHelp))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cambia el look and feel seleccionado
     *
     * @param evt
     */
    private void jComboLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLookAndFeelActionPerformed
        try {
            // Guarda el índice seleccionado
            UIManager.LookAndFeelInfo lookAndFeel = UIManager.getInstalledLookAndFeels()[jComboLookAndFeel.getSelectedIndex()];
            UIManager.setLookAndFeel(lookAndFeel.getClassName());

            // Aplica los cambios
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(this, "ERROR ASIGNANDO LOOK AND FEEL", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jComboLookAndFeelActionPerformed

    private void jMenuItemCiudadFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCiudadFechaActionPerformed
        RegistroCiudadFecha jDialogCiudadFecha = new RegistroCiudadFecha(this, true);
        jDialogCiudadFecha.setVisible(true);

        refrescarDatosTabla();
    }//GEN-LAST:event_jMenuItemCiudadFechaActionPerformed

    private void jMenuItemTemperaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTemperaturasActionPerformed
        RegistroTemperaturas jDialogTemperaturas = new RegistroTemperaturas(this, true);
        jDialogTemperaturas.setVisible(true);

        refrescarDatosTabla();
    }//GEN-LAST:event_jMenuItemTemperaturasActionPerformed

    private void jButtonEliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCiudadActionPerformed
        if (LogicaVisitas.getListaVisitas().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay registros para poder eliminar", "NO REGISTROS", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String ciudadBorrar = JOptionPane.showInputDialog(this, "Introduce el nombre de la ciudad a eliminar", "Eliminar ciudad", JOptionPane.QUESTION_MESSAGE);

        if (ciudadBorrar == null) {
            JOptionPane.showMessageDialog(this, "Operación cancelada", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (ciudadBorrar.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No has introducido ningún nombre", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Visita visitaBorrar = LogicaVisitas.getListaVisitas().stream()
                .filter(v -> v.getCiudad().equalsIgnoreCase(ciudadBorrar))
                .findFirst().orElse(null);
        if (visitaBorrar == null) {
            JOptionPane.showMessageDialog(this, "No hay ninguna coincidencia con la ciudad: " + ciudadBorrar, "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la ciudad " + visitaBorrar.getCiudad() + "?", "¿SEGURO?", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "De acuerdo, eliminamos la visita a la ciudad " + visitaBorrar.getCiudad() + " en la estación " + visitaBorrar.getEstacion(), "Eliminación de visita", JOptionPane.INFORMATION_MESSAGE);
            LogicaVisitas.getListaVisitas().remove(visitaBorrar);
            refrescarDatosTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Sabía que no te querías perder la visita a la ciudad " + visitaBorrar.getCiudad() + " en la fecha " + sdf.format(visitaBorrar.getFechaPrevista()), "Eliminación de visita cancelada", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarCiudadActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        ayuda.mostrarAyuda();
    }//GEN-LAST:event_jButtonHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarCiudad;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JComboBox<String> jComboLookAndFeel;
    private javax.swing.JLabel jLabelImgEstacion;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCiudadFecha;
    private javax.swing.JMenuItem jMenuItemTemperaturas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

    /**
     * Muestra los Look And Feel
     */
    private void mostrarLookAndFeel() {
        // Creamos el modelo del ComboBox
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();

        for (UIManager.LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels()) {
            dcm.addElement(lfi.getName());

            // Asigna el modelo al comboBox creado
            jComboLookAndFeel.setModel(dcm);
        }
    }

    /**
     * Cambia el icono de la app
     */
    private void cambiarIconoApp() {
        // Carga la imagen
        ImageIcon iconoApp = new ImageIcon(getClass().getResource("/gui/imgs/icono.jpg"));
        // Lo convierte de icon a image
        Image iconoImagen = iconoApp.getImage();
        // Cambia el icono
        this.setIconImage(iconoImagen);
    }

    /**
     * Inicializa los componentes de la tabla y su ordenación
     */
    private void inicializarTabla() {
        // Inicializar dtm, asegurando que ordena bien al ser un dato Double
        dtm = new DefaultTableModel() {
            @Override
            public Class getColumnClass(int columna) {
                if (columna != 5) {
                } else {
                    return Double.class;
                }
                return Object.class;
            }
        };

        String[] titulos = new String[]{"Ciudad", "Fecha", "Estación", "Tº mín", "Tº máx", "Tº promedio"};

        dtm.setColumnIdentifiers(titulos);

        jTable.setModel(dtm);

        // Sorter
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable.getModel());

        jTable.setRowSorter(sorter);

        // Configurar orden
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        // De mayor a menor

        sortKeys.add(
                new RowSorter.SortKey(5, SortOrder.DESCENDING));

        // Aplicamos orden
        sorter.setSortKeys(sortKeys);

        // Refrescamos los datos
        refrescarDatosTabla();
    }

    /**
     * Refresca los datos de la tabla
     */
    private void refrescarDatosTabla() {
        dtm.setRowCount(0);

        // Recoge los datos de la lista
        LogicaVisitas.getListaVisitas().forEach(v -> dtm.addRow(new Object[]{v.getCiudad(), sdf.format(v.getFechaPrevista()), v.getEstacion(), v.getTempMin(), v.getTempMax(), v.getTempPromedio()}));

        // Forzar la reordenación
        RowSorter<? extends TableModel> sorter = jTable.getRowSorter();
        if (sorter != null) {
            ((TableRowSorter<?>) sorter).sort();
        }

        // AÑADIR IMAGEN DE ESTACIÓN ÚLTIMA VISITA
        if (LogicaVisitas.getListaVisitas().isEmpty()) {
            return;
        }

        Visita ultimaVisita = LogicaVisitas.getListaVisitas().getLast();
        ImageIcon imgOriginal = new ImageIcon(getClass().getResource("/gui/imgs/" + ultimaVisita.getEstacion().toLowerCase() + ".png"));

        Image img = imgOriginal.getImage();
        // Escala la imagen al tamaño del jLabel
        Image scaledImg = img.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);

        jLabelImgEstacion.setIcon(new ImageIcon(scaledImg));
    }

}
